<?php

namespace Database\Seeders;

use App\Models\AircraftType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AircraftTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $aircraft = [
            [
                'name'=> 'N262',
                'max_passengers'=>29,
                'engine_type'=> 'PT6A45',
                'engines'=>2
            ],
            [
                'name'=> 'S601',
                'max_passengers'=>14,
                'engine_type'=>'JT15D-4',
                'engines'=>2
            ],
            [
                'name'=>'A306',
                'max_passengers'=>266,
                'engine_type'=>'CF6-80C2A1',
                'engines'=>2
            ],
            [
                'name'=>'A3ST',
                'max_passengers'=>0,
                'engine_type'=>'CF6-80C2A8',
                'engines'=>2
            ],
            [
                'name'=>'A30B',
                'max_passengers'=>336,
                'engine_type'=>'CF6-50C',
                'engines'=>2
            ],
            [
                'name'=>'A310',
                'max_passengers'=>280,
                'engine_type'=>'CF6-80C2A2',
                'engines'=>2
            ],
            [
                'name'=>'A318',
                'max_passengers'=>107,
                'engine_type'=>'PW-6000',
                'engines'=>2
            ],
            [
                'name'=>'A319',
                'max_passengers'=>124,
                'engine_type'=>'CFM56-5A',
                'engines'=>2
            ],
            [
                'name'=>'A320',
                'max_passengers'=>179,
                'engine_type'=>'CFM56-5A1',
                'engines'=>2
            ],
            [
                'name'=>'A321',
                'max_passengers'=>220,
                'engine_type'=>'V2530-A5',
                'engines'=>2
            ],
            [
                'name'=>'A332',
                'max_passengers'=>256,
                'engine_type'=>'CF6-80E1A2',
                'engines'=>2
            ],
            [
                'name'=>'A333',
                'max_passengers'=>440,
                'engine_type'=>'CF6-80E1A2',
                'engines'=>2
            ],
            [
                'name'=>'A342',
                'max_passengers'=>303,
                'engine_type'=>'CFM56-5C',
                'engines'=>4
            ],
            [
                'name'=>'A343',
                'max_passengers'=>335,
                'engine_type'=>'CFM56-5C',
                'engines'=>4
            ],
            [
                'name'=>'A345',
                'max_passengers'=>316,
                'engine_type'=>'Trent 553-61',
                'engines'=>4
            ],
            [
                'name'=>'A346',
                'max_passengers'=>380,
                'engine_type'=>'Trent 556-61',
                'engines'=>4
            ],
            [
                'name'=>'A388',
                'max_passengers'=>555,
                'engine_type'=>'GP-7270',
                'engines'=>4
            ],
            [
                'name'=>'B703',
                'max_passengers'=>219,
                'engine_type'=>'JT3D-3B',
                'engines'=>4
            ],
            [
                'name'=>'B712',
                'max_passengers'=>117,
                'engine_type'=>'BR700-715A1-30',
                'engines'=>2
            ],
            [
                'name'=>'B720',
                'max_passengers'=>165,
                'engine_type'=>'JT3D-7 series',
                'engines'=>4
            ],
            [
                'name'=>'B721',
                'max_passengers'=>131,
                'engine_type'=>'JT8D-11',
                'engines'=>3
            ],
            [
                'name'=>'B722',
                'max_passengers'=>189,
                'engine_type'=>'JT8D-17R',
                'engines'=>3
            ],
            [
                'name'=>'B732',
                'max_passengers'=>115,
                'engine_type'=>'JT8D-17R',
                'engines'=>2
            ],
            [
                'name'=>'B733',
                'max_passengers'=>141,
                'engine_type'=>'CFM56-3B-2',
                'engines'=>2
            ],
            [
                'name'=>'B734',
                'max_passengers'=>188,
                'engine_type'=>'CFM56-3B-2',
                'engines'=>2
            ],
            [
                'name'=>'B735',
                'max_passengers'=>132,
                'engine_type'=>'CFM56-3C-1',
                'engines'=>2
            ],
            [
                'name'=>'B736',
                'max_passengers'=>132,
                'engine_type'=>'CFM56-7B22',
                'engines'=>2
            ],
            [
                'name'=>'B737',
                'max_passengers'=>149,
                'engine_type'=>'CFM56-7B24',
                'engines'=>2
            ],
            [
                'name'=>'B738',
                'max_passengers'=>189,
                'engine_type'=>'CFM56-7B27',
                'engines'=>2
            ],
            [
                'name'=>'B739',
                'max_passengers'=>189,
                'engine_type'=>'CFM56-7B27',
                'engines'=>2
            ],
            [
                'name'=>'B741',
                'max_passengers'=>500,
                'engine_type'=>'JT9D-7A',
                'engines'=>4
            ],
            [
                'name'=>'B742',
                'max_passengers'=>500,
                'engine_type'=>'CF6-80C2A1',
                'engines'=>4
            ],
            [
                'name'=>'B743',
                'max_passengers'=>470,
                'engine_type'=>'JT9D-7R4G2',
                'engines'=>4
            ],
            [
                'name'=>'B744',
                'max_passengers'=>568,
                'engine_type'=>'PW4056',
                'engines'=>4
            ],
            [
                'name'=>'B745',
                'max_passengers'=>440,
                'engine_type'=>'RB211-524B series',
                'engines'=>4
            ],
            [
                'name'=>'B752',
                'max_passengers'=>239,
                'engine_type'=>'RB211-535C',
                'engines'=>2
            ],
            [
                'name'=>'B753',
                'max_passengers'=>289,
                'engine_type'=>'RB211-535E4B',
                'engines'=>2
            ],
            [
                'name'=>'B762',
                'max_passengers'=>290,
                'engine_type'=>'JT9D-7R4D, -7R4D1',
                'engines'=>2
            ],
            [
                'name'=>'B763',
                'max_passengers'=>350,
                'engine_type'=>'JT9D-7R4D, -7R4D1',
                'engines'=>2
            ],
            [
                'name'=>'B764',
                'max_passengers'=>245,
                'engine_type'=>'PW4062',
                'engines'=>2
            ],
            [
                'name'=>'B772',
                'max_passengers'=>440,
                'engine_type'=>'PW4074',
                'engines'=>2
            ],
            [
                'name'=>'B773',
                'max_passengers'=>550,
                'engine_type'=>'PW4090',
                'engines'=>2
            ],
            [
                'name'=>'B788',
                'max_passengers'=>250,
                'engine_type'=>'GEnx-1B54',
                'engines'=>2
            ],
            [
                'name'=>'CL30',
                'max_passengers'=>15,
                'engine_type'=>'AS907-1-1A',
                'engines'=>2
            ],
            [
                'name'=>'GLF2',
                'max_passengers'=>19,
                'engine_type'=>'Spey 555',
                'engines'=>2
            ]
            ];
        //
            foreach($aircraft as $planes){
                AircraftType::create($planes);
            }
    }
}
